learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/router.ex
defmodule LearnSymbolsWeb.Router do
  @moduledoc false
  use LearnSymbolsWeb, :router

  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LearnSymbolsWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/profile", ProfileController, :profile


    get "/start", LearnController, :start
    get "/logout", AuthController, :logout
    post "/answer", LearnController, :answer
  end

  scope "/auth", LearnSymbolsWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback

  end

  # Other scopes may use custom stacks.
  # scope "/api", LearnSymbolsWeb do
  #   pipe_through :api
  # end
end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/controllers/auth_controller.ex
defmodule LearnSymbolsWeb.AuthController do
  use LearnSymbolsWeb, :controller
  plug Ueberauth

  alias Ueberauth.Strategy.Helpers
  alias LearnSymbolsWeb.User

  require Logger


  @moduledoc """
    Handles Auth0 authentication and callbacks
  """

  def logout(conn, _params) do
    conn
    |> put_flash(:info, "You have been logged out!")
    |> configure_session(drop: true)
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do
    conn
    |> put_flash(:error, "Failed to authenticate.")
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    Logger.debug "in auth callback"
    case User.find_or_create(auth) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Successfully authenticated as " <> user.name <> ".")
        |> put_session(:current_user, user)
        |> redirect(to: "/")
      {:error, reason} ->
        conn
        |> put_flash(:error, reason)
        |> redirect(to: "/")
    end
  end
end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/controllers/learn_controller.ex
defmodule LearnSymbolsWeb.LearnController do
  use LearnSymbolsWeb, :controller

  require Logger
  require Poison

  plug :secure

  defp secure(conn, _params) do
    user = get_session(conn, :current_user)
    case user do
      nil ->
        conn
        |> redirect(to: "/auth/auth0")
        |> halt
      _ ->
        conn
        |> assign(:current_user, user)
    end
  end

  def start(conn, _params) do
    with user <- conn.assigns[:current_user],
         {:ok, symbol} <- LearnSymbols.get_symbol(user.id) do
      render conn, "learn.html", %{symbol: symbol.symbol, symbol_id: symbol.id}
    else
      err -> err
    end
  end

  def answer(conn, %{"answer" => answer, "symbol_id" => symbol_id}) do
    user = conn.assigns[:current_user]
    answer_atom = case answer do
      "yes" -> :yes
      _ -> :no
    end

    with {:ok, _} <- LearnSymbols.answer(user.id, symbol_id, answer_atom),
         {:ok, symbol} = LearnSymbols.get_symbol(user.id)do
      render conn, "learn.html", %{symbol: symbol.symbol, symbol_id: symbol.id}
      else
      err -> err
    end
  end
end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/controllers/page_controller.ex
defmodule LearnSymbolsWeb.PageController do
  use LearnSymbolsWeb, :controller

  def index(conn, _params) do
    render conn, "index.html", current_user: get_session(conn, :current_user)
  end
end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/controllers/profile_controller.ex
defmodule LearnSymbolsWeb.ProfileController do
  use LearnSymbolsWeb, :controller
  alias LearnSymbols

  plug :secure

  defp secure(conn, _params) do
    user = get_session(conn, :current_user)
    case user do
      nil ->
        conn
        |> redirect(to: "/auth/auth0")
        |> halt
      _ ->
        conn
        |> assign(:current_user, user)
    end
  end

  def profile(conn, _params) do
    with user <- conn.assigns[:current_user],
         {:ok, profile} <- LearnSymbols.get_user_profile(user.id) do
      render conn, "profile.html", %{profile: profile}
    else
      err -> err
    end
  end
end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/live/learn_live_view.ex
defmodule LearnSymbolsWeb.LearnLiveView do
  use Phoenix.LiveView

  alias LearnSymbols

  require Logger
  require Poison

  @moduledoc false


  def render(assigns) do
    Phoenix.View.render(LearnSymbolsWeb.PageView, "learn_live.html", assigns)
  end

  def mount(%{user_id: user_id, symbols: symbols}, socket) do
    {:ok, assign(socket, user_id: user_id, symbols: symbols)}
  end


end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/live/profile_symbols_live.ex
defmodule LearnSymbolsWeb.ProfileSymbolsLiveView do
  use Phoenix.LiveView

  alias LearnSymbols

  require Logger
  require Poison

  @moduledoc false


  def render(assigns) do
    Phoenix.View.render(LearnSymbolsWeb.PageView, "profile_symbols_live.html", assigns)
  end

  def mount(%{user_id: user_id}, socket) do
    {:ok, user} = LearnSymbols.get_user_profile(user_id)
    {:ok, assign(socket, user_id: user_id, symbols: user.symbols)}
  end

  def handle_event(
        "delete-symbol",
        symbol_id,
        %{
          assigns: %{
            user_id: user_id
          }
        } = socket
      ) do
    Logger.debug symbol_id
    :ok = LearnSymbols.remove_symbol_from_user(user_id, symbol_id)
    {:ok, user} = LearnSymbols.get_user_profile(user_id)
    {:noreply, assign(socket, symbols: user.symbols)}
  end

  def handle_event("validate", %{"create_symbol" => symbol}, %{assigns: assigns} = socket) do
    # Logger.debug assigns
    {:noreply, assign(socket, assigns)}
  end

  def handle_event(
        "create",
        %{"create_symbol" => symbol},
        %{
          assigns: %{
            user_id: user_id
          }
        } = socket
      ) do
    LearnSymbols.add_symbol_to_user(user_id, symbol["symbol"])
    {:ok, user} = LearnSymbols.get_user_profile(user_id)
    {:noreply, assign(socket, symbols: user.symbols)}
  end


end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/views/auth_view.ex
defmodule LearnSymbolsWeb.AuthView do
  @moduledoc false

  use LearnSymbolsWeb, :view

end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/views/error_view.ex
defmodule LearnSymbolsWeb.ErrorView do
  use LearnSymbolsWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/views/layout_view.ex
defmodule LearnSymbolsWeb.LayoutView do
  use LearnSymbolsWeb, :view
end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/views/learn/learn_view.ex
defmodule LearnSymbolsWeb.LearnView do
  use LearnSymbolsWeb, :view

end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/views/page_view.ex
defmodule LearnSymbolsWeb.PageView do
  use LearnSymbolsWeb, :view
end

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>LearnSymbols · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="/">Home</a></li>
            <%= if @current_user do %>
              <li><a href="/start">Start</a></li>
              <li><a href="/profile">Profile / Setup</a></li>
              <li class="active"><a href="/logout">Logout</a></li>
            <% else %>
              <li><a href="/auth/auth0">Login</a></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://dinoroar.io/" class="phx-logo">
          <img src="https://storage.googleapis.com/www.dinoroar.io/twitter-header.png" alt="DinoRoar Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/templates/learn/learn.html.eex
<section class="phx-hero">
  <h1>Say what you See!</h1>
</section>

<section >
  <article class="say-what-you-see"><%= @symbol %></article>
  <article class="answers">
    <h2>Did you get it right?</h2>

    <%= button "Yes",  to: Routes.learn_path(@conn, :answer, %{symbol_id: @symbol_id, answer: :yes}), method: "post" %>
    <%= button "No",  to: Routes.learn_path(@conn, :answer, %{symbol_id: @symbol_id, answer: :no}), method: "post" %>
  </article>

</section>

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1>Lets Learn Letters</h1>
  <p>A simple and fun way to learn letters.</p>
</section>

<section class="row">
  <article class="column">
    <h2>How does this work?</h2>
    <p>A letter will be shown, you try to say the letter. Hit the button and listen to it being said back to you.</p>
    <p>If you got it right choose if it was easy or hard or if you got it wrong choose wrong</p>
    <p>The letters you get wrong will show more often</p>

    <%= button "Start",  to: Routes.learn_path(@conn, :start, %{dave: ""}), method: "get" %>
  </article>
</section>

<section>
<h2></h2>
</section>

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/templates/page/learn_live.html.leex
<section class="phx-hero">
  <h1>Say what you See!</h1>
</section>

<section >

  <article class="answers">
    <h2>Did you get it right?</h2>


  </article>

</section>

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/templates/page/profile_symbols_live.html.leex
<section >
  <article class="answers">
    <h2>Symbols</h2>

<div class="container">
    <%= for symbol <- @symbols do %>

    <div class="row">
      <div class="column"><%= symbol.symbol %></div>
      <div class="column"><%= DateTime.to_string( symbol.next_show) %></div>
      <div class="column">
        <button phx-click="delete-symbol" phx-value="<%= symbol.id %>">Delete Symbol</button>
      </div>
    </div>
    <% end %>
    <div class="row">
    <%= f = form_for LearnSymbolsWeb.CreateSymbol.changeset(%LearnSymbolsWeb.CreateSymbol{}) , "#", [phx_change: :validate, phx_submit: :create] %>
      <%= label f, :symbol %>
      <%= text_input f, :symbol %>
      <%= error_tag f, :symbol %>

      <div>
        <%= submit "Create", phx_disable_with: "Creating..." %>
      </div>
    </form>


    </div>
</div>

  </article>

</section>

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/templates/profile/profile.html.eex
<section class="phx-hero">
<h1>user profile</h1>


</section>
<section class="row">
  <article class="column">
    <div><%= @profile.name %></div>
    <div>Symbols being learnt</div>
      <%= Phoenix.LiveView.live_render(@conn, LearnSymbolsWeb.ProfileSymbolsLiveView, session: %{user_id: @profile.id, symbols: @profile.symbols}) %>
    <%= link "Start", to: Routes.learn_path(@conn, :start, %{id: @profile.id})   %>
  </article>
</section>

learn_symbols_umbrella/apps/learn_symbols_web/lib/learn_symbols_web/templates/profile/symbol.html.eex
<div>
  <%= @symbol %>
  <%= button "Remove",  to: Routes.learn_path(@conn, :start, %{dave: ""}), method: "post" %>
</div>